### ISSUE TITLE
CSS support

### ISSUE THREAD

**Issue by ctrlplusb** [chromakode/isolated-core#2]
Fantastic library.  I have been trying it out with a React project.  Works great, except for my CSS (webpack bundled CSS modules) isn't brought along for the ride.

Looking through your docs it looks like you are specifically targeting script reloads.  

Do you reckon there is any possibility that I could use isolated-core to hot swap a CSS file?

**Comment by chromakode** [comment]
Glad to hear it! Are you using [`style-loader`](https://github.com/webpack/style-loader) to inject your stylesheets into the DOM? I've looked into this, unfortunately it gets tripped up because it appends the `<style>` tag to the `<head>` inside the core iframe, not the outer document. I haven't been able to find an option to work around this -- it'd probably need a patch to add more flexibility around where it appends the `<style>` tag.

Presently, there are a couple alternatives. The demo site uses React to [inline CSS into a style tag](https://github.com/chromakode/isolated-core/blob/bd6b3e3fe264c26ce6d9f94ecb2005cec6a4ddd0/demo/src/DemoUI.js#L67), which works ok. You can use the `css-loader` without `style-loader` to get the source and do with it what you please. For larger stylesheets an object url is probably the way to go, as `style-loader` does it.

Hope this helps!

**Comment by ctrlplusb** [comment]
Well met!  I was just looking into the style-loader scenario myself! I noticed the same thing you did and was trying to see if there was a post-core-loaded-promise-then type of hook I could use to try and manually clone the style from the iframe into the outer document.  That could be a win of sorts.

The inline CSS approach sounds interesting, I'll def have a look. I may just need to just ensure my globals are then defined and imported separately.

Thanks for the quick response. 

I am really loving isolated core.  I am trying to get a fully hot reloading server and client boilerplate going and this library has helped me loads - the React HMR stuff always has issues.  If I can solve the CSS issue I am done.  What a dream that would be for my future dev experiences!

**Comment by chromakode** [comment]
> I noticed the same thing you did and was trying to see if there was a post-core-loaded-promise-then type of hook I could use to try and manually clone the style from the iframe into the outer document.

Have you checked to see if the `<style>` node exists at the time your core's `attach()` function is called? I'd advise manipulating the `<style>` element inside the core `attach`/`detach` callbacks. I haven't tried doing this -- I imagine one advantage is you can use the object url created by `style-loader`, but I haven't tested whether that works across iframe boundaries. 

> I am really loving isolated core. I am trying to get a fully hot reloading server and client boilerplate going and this library has helped me loads - the React HMR stuff always has issues. If I can solve the CSS issue I am done. What a dream that would be for my future dev experiences!

Woot! It is definitely super satisfying to get hot reloading working smoothly. :grinning: 

One note regarding client reloading: I've got a small [setup-core branch](https://github.com/chromakode/isolated-core/commit/c89f5d1234733bcacd0badedabff1fef49168105) in progress that improves the API for state transfer. If that would be useful to you, I can bump it up in my queue :)

Another detail with this approach is that React (at least up to 0.14 -- haven't dug into 15 yet) doesn't know how to reuse DOM when the instances change. This leads to a lot of the complexities of @gaearon's excellent [React-Proxy](https://github.com/gaearon/react-proxy) library. There may be other UI component libraries that will diff existing DOM (I've wondered if [Preact](https://github.com/developit/preact/) can), but I'm hopeful that in the future it'll be simpler to do this with React. In the mean time, input components will get reset unless their state is managed by React. In production that's often ok, since you'll typically offer the user to accept an update at a time that is convenient for them.

---

![Well met!](https://i.ytimg.com/vi/4k2zrU9Cr7Q/maxresdefault.jpg)

(sorry, wasn't sure if you intended a bit of Hearthstone humor there)

**Comment by ctrlplusb** [comment]
Hahaha, no idea about Hearthstone, I just had an overwhelming desire to write that at the time.  I honestly have no idea why. 

Brilliant, thanks for these insights!  I am going to try and see how far I can get with lifting the CSS out of the iframe at some point this week.  I'll let you know how it goes.

The swap state thing is definitely useful!  Although it's not urgent for me as I am using some middleware on redux to store the current state in the global window.

Thanks again for the info!

**Comment by ctrlplusb** [comment]
Hi!

Long time, I got ripped off into a high pressure contract and haven't been able to touch this.  Finally have a bit of free time again.

So, good news, I have been able to use your recommendation; hooking into the `attach` handler and copying over the style nodes.  It works perfectly!  This is like ultra awesome.

I am just developing some logic so that subsequent updates will replace previously mounted style nodes, but it looks like it's entirely possible.  :)

Here is a very naive approach:

``` javascript
window._core.uidocument.head.appendChild(
  window.document.querySelector(`link[rel=stylesheet]`)
)
```

Shall keep you posted with my progress in making this a bit more solid and then perhaps we could think of making a native extension to your library?

**Comment by ctrlplusb** [comment]
🎉 

Got it working awesomely!!

``` javascript
import { unmountComponentAtNode } from 'react-dom'
import main from '../../src/frontend/main'

export function init (core) {
  core.ready({
    attach (uidocument) {
      // Get the DOM Element that will host our React application.
      const container = uidocument.getElementById('main')

      // Mount our application to the container.
      main(container)

      // Firstly clear down any cloned styles.
      Array.prototype.forEach.call(
        window._core.uidocument.querySelectorAll('link[data-core-styles]'),
        (style) => {
          style.parent.removeChild(style)
        }
      )

      // Now clone over any styles that may exist in the iframe.
      Array.prototype.forEach.call(
        document.querySelectorAll('link[rel=stylesheet]'),
        (style) => {
          const stylesClone = document.createElement('link')
          stylesClone.rel = 'stylesheet'
          stylesClone.href = style.href
          stylesClone['data-core-styles'] = true
          window._core.uidocument.head.appendChild(stylesClone)
        }
      )
    },

    detach (uidocument) {
      unmountComponentAtNode(uidocument.getElementById('main'))
    }
  })
}
```

I am in heaven now!  Hot reloading server and client SSR React application.
